[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
serde_json = "=1.0.151"
xtrace-desktop = { path = "../apps/desktop/src-tauri" }
xt-fixtures = { path = "../crates/xt-fixtures" }

[dev-dependencies]
tempfile = "=3.27.0"
