#[cfg(all(debug_assertions, feature = "fixtures"))]
use xtrace_desktop::dto::FixtureExport;
use xtrace_desktop::state::{AppState, StartupOptions, StateError};

/// Fixture startup never indexes live data: the shell export carries the
/// disabled index the app reports in fixture mode.
#[cfg(all(debug_assertions, feature = "fixtures"))]
fn expected_native_index() -> xtrace_desktop::dto::NativeIndexStatus {
    use std::sync::Arc;
    use xtrace_desktop::native_index::NativeIndex;
    NativeIndex::disabled("fixture mode uses a disposable database", Arc::new(|_| {})).status()
}

#[test]
fn fixture_mode_data_dir_override_wins_and_live_store_persists() {
    let root = tempfile::TempDir::new().unwrap();
    let path = root.path().join("explicit");
    std::fs::create_dir_all(root.path().join("home")).unwrap();
    let state = AppState::build(
        StartupOptions {
            data_dir: Some(path.clone()),
            ..Default::default()
        },
        || panic!("default path must not be resolved"),
        || Ok(root.path().join("home")),
    )
    .unwrap();
    assert_eq!(state.app_info().data_dir, path.to_str().unwrap());
    assert_eq!(state.app_info().schema_version, 5);
    assert_eq!(state.app_info().fixture, None);
    assert!(!state.app_info().listening);
    assert_eq!(
        serde_json::to_value(state.db_counts().unwrap()).unwrap(),
        serde_json::json!({"sessions":0,"records":0,"usage":0})
    );
    state.shutdown();
    state.shutdown();
    assert!(matches!(state.db_counts(), Err(StateError::Closed)));
    assert!(path.join("xtrace.db").exists());
    let home = root.path().join("home");
    AppState::build(StartupOptions::default(), || Ok(path), || Ok(home)).unwrap();
}

#[test]
fn fixture_mode_options_have_explicit_precedence_and_validation() {
    let options =
        StartupOptions::parse(None, Some("F2".into()), ["--fixture".into(), "F1".into()]).unwrap();
    assert_eq!(options.fixture.as_deref(), Some("F1"));
    for args in [
        vec!["--fixture"],
        vec!["--fixture="],
        vec!["--fixture", "--fixture"],
        vec!["--fixture=F1", "--fixture=F2"],
    ] {
        assert!(StartupOptions::parse(None, None, args.into_iter().map(String::from)).is_err());
    }
    assert!(StartupOptions::parse(None, Some(String::new().into()), []).is_err());
}

#[cfg(not(all(debug_assertions, feature = "fixtures")))]
#[test]
fn fixture_mode_is_disabled_without_debug_feature() {
    let result = AppState::build(
        StartupOptions {
            fixture: Some("F1".into()),
            ..Default::default()
        },
        || panic!("fixture must not resolve live directory"),
        || panic!("fixture must not resolve the home directory"),
    );
    assert!(matches!(result, Err(StateError::FixtureDisabled)));
}

#[cfg(all(debug_assertions, feature = "fixtures"))]
#[test]
fn fixture_mode_builds_isolated_database_and_generated_export_parity() {
    let root = tempfile::TempDir::new().unwrap();
    let build = || {
        AppState::build(
            StartupOptions {
                data_dir: Some(root.path().into()),
                fixture: Some("F1".into()),
                ..Default::default()
            },
            || panic!("fixture must not resolve live directory"),
            || panic!("fixture must not resolve the home directory"),
        )
        .unwrap()
    };
    let first = build();
    let second = build();
    assert_ne!(first.app_info().data_dir, second.app_info().data_dir);
    let path = std::path::PathBuf::from(first.app_info().data_dir.clone());
    let mut app_info = first.app_info();
    assert_eq!(app_info.fixture.as_deref(), Some("F1"));
    app_info.data_dir = "fixture://F1".into();
    let export = FixtureExport {
        app_info,
        db_counts: first.db_counts().unwrap(),
        native_index: expected_native_index(),
        sessions: first.sessions_list("", None, None).unwrap(),
        dashboards: [7, 14, 30]
            .into_iter()
            .map(|days| first.metrics_dashboard(days).unwrap())
            .collect(),
    };
    // Compare the exact generated bytes: serde_json's default float parser is
    // not round-trip exact, so parsed values can differ in the last bit.
    assert_eq!(
        serde_json::to_string_pretty(&export).unwrap() + "\n",
        include_str!("../../ui/fixtures/F1.json")
    );
    let exported = serde_json::to_value(export).unwrap();
    assert_eq!(
        exported["db_counts"],
        serde_json::json!({"sessions":1,"records":25,"usage":15})
    );
    first.shutdown();
    assert!(!path.exists());
    assert!(matches!(first.db_counts(), Err(StateError::Closed)));
    first.shutdown();
    assert!(std::path::Path::new(&second.app_info().data_dir).exists());
    let second_path = std::path::PathBuf::from(second.app_info().data_dir);
    drop(second);
    assert!(!second_path.exists());
}

#[cfg(all(debug_assertions, feature = "fixtures"))]
#[test]
fn fixture_mode_rejects_skeletons_and_invalid_ids_without_live_reads() {
    for fixture in ["F2", "F20", "../F1", "F999"] {
        let result = AppState::build(
            StartupOptions {
                fixture: Some(fixture.into()),
                ..Default::default()
            },
            || panic!("fixture must not resolve live directory"),
            || panic!("fixture must not resolve the home directory"),
        );
        assert!(matches!(result, Err(StateError::FixtureInvalid)));
    }
}

#[cfg(unix)]
#[test]
fn fixture_mode_non_unicode_selection_fails_before_live_startup() {
    use std::os::unix::ffi::OsStringExt;
    let value = std::ffi::OsString::from_vec(vec![0xff]);
    assert!(matches!(
        StartupOptions::parse(None, Some(value), []),
        Err(StateError::InvalidOption)
    ));
}

#[test]
fn a_data_directory_inside_the_native_history_is_refused_before_anything_is_written() {
    // The database destination is validated against the native home before
    // the directory is created or SQLite opens: nothing lands in `.claude`.
    let root = tempfile::TempDir::new().unwrap();
    let home = root.path().join("home");
    std::fs::create_dir_all(home.join(".claude/projects")).unwrap();
    let inside = home.join(".claude/xtrace-data");
    let result = AppState::build(
        StartupOptions {
            data_dir: Some(inside.clone()),
            native_home: Some(home.clone()),
            ..Default::default()
        },
        || panic!("an explicit data directory needs no default"),
        || panic!("an explicit home needs no default"),
    );
    assert!(
        matches!(result, Err(StateError::IndexDestination(reason)) if reason.contains("native history")),
        "{:?}",
        result.err()
    );
    assert!(
        !inside.exists(),
        "no directory was created inside the native history"
    );
    assert!(
        std::fs::read_dir(home.join(".claude"))
            .unwrap()
            .all(|entry| entry.unwrap().file_name() == "projects"),
        "no database files were written into the native history"
    );
    // The same home with a data directory beside it opens normally.
    let beside = root.path().join("data");
    let state = AppState::build(
        StartupOptions {
            data_dir: Some(beside.clone()),
            native_home: Some(home.clone()),
            ..Default::default()
        },
        || panic!("an explicit data directory needs no default"),
        || panic!("an explicit home needs no default"),
    )
    .unwrap();
    assert_eq!(state.native_home(), Some(home.as_path()));
    assert_eq!(
        state.database_path(),
        Some(beside.join("xtrace.db").as_path())
    );
    state.shutdown();
}

#[cfg(unix)]
#[test]
fn an_unreadable_project_directory_does_not_prevent_startup() {
    use std::os::unix::fs::PermissionsExt;
    // A source-access problem is the index's to report, not a startup failure.
    let root = tempfile::TempDir::new().unwrap();
    let home = root.path().join("home");
    let sealed = home.join(".claude/projects/-repo-sealed");
    std::fs::create_dir_all(&sealed).unwrap();
    std::fs::set_permissions(&sealed, std::fs::Permissions::from_mode(0o000)).unwrap();
    let built = AppState::build(
        StartupOptions {
            data_dir: Some(root.path().join("data")),
            native_home: Some(home.clone()),
            ..Default::default()
        },
        || panic!("an explicit data directory needs no default"),
        || panic!("an explicit home needs no default"),
    );
    std::fs::set_permissions(&sealed, std::fs::Permissions::from_mode(0o755)).unwrap();
    let state = built.unwrap();
    assert_eq!(state.native_home(), Some(home.as_path()));
    state.shutdown();
}

#[test]
fn a_native_home_that_does_not_exist_is_refused_at_startup() {
    // An absent home could not be watched (there is no ancestor to cover
    // it), so the index would stay degraded and empty; refuse it instead.
    let root = tempfile::TempDir::new().unwrap();
    let result = AppState::build(
        StartupOptions {
            data_dir: Some(root.path().join("data")),
            native_home: Some(root.path().join("absent-home")),
            ..Default::default()
        },
        || panic!("an explicit data directory needs no default"),
        || panic!("an explicit home needs no default"),
    );
    assert!(
        matches!(result, Err(StateError::NativeHome)),
        "{:?}",
        result.err()
    );
    assert!(!root.path().join("data").exists());
}

#[cfg(unix)]
#[test]
fn a_dangling_source_root_alias_does_not_prevent_startup() {
    // `~/.codex` pointing nowhere is the Codex scan's to report as missing.
    let root = tempfile::TempDir::new().unwrap();
    let home = root.path().join("home");
    std::fs::create_dir_all(home.join(".claude/projects")).unwrap();
    std::os::unix::fs::symlink(root.path().join("absent"), home.join(".codex")).unwrap();
    let state = AppState::build(
        StartupOptions {
            data_dir: Some(root.path().join("data")),
            native_home: Some(home.clone()),
            ..Default::default()
        },
        || panic!("an explicit data directory needs no default"),
        || panic!("an explicit home needs no default"),
    )
    .unwrap();
    assert_eq!(state.native_home(), Some(home.as_path()));
    state.shutdown();
}
