import { act, cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { SessionTranscript } from './SessionTranscript';
import { exceedsClamp } from './TranscriptText';
import type { TranscriptRecord } from './transcript-view';

/**
 * When an answer is parsed, and what a long session costs.
 *
 * `react-markdown` is wrapped so each parse is counted: its component parses synchronously on
 * every call and keeps nothing between calls, so a call is a parse. Every record here is
 * generated by this test.
 */
const parses = vi.hoisted(() => ({ count: 0 }));
vi.mock('react-markdown', async (importOriginal) => {
  const actual = await importOriginal<typeof import('react-markdown')>();
  const Counted = (options: Parameters<typeof actual.default>[0]) => {
    parses.count += 1;
    return actual.default(options);
  };
  return { ...actual, default: Counted };
});

beforeEach(() => {
  parses.count = 0;
});
afterEach(cleanup);

function answer(n: number): string {
  return [
    `### Step ${n}`,
    '',
    `Checked **${n}** fixtures with \`synthetic-tool --n ${n}\`; see [notes](./notes-${n}.md).`,
    '',
    '- read the input',
    '- ran the check',
    '',
    '| field | value |',
    '| --- | --- |',
    `| rows | ${n * 3} |`,
    '',
    '```sh',
    `synthetic-tool --n ${n}`,
    '```',
  ].join('\n');
}

function longAnswer(n: number): string {
  return [
    `# Long report ${n}`,
    ...Array.from({ length: 60 }, (_, row) => `- item ${row + 1} of report ${n} with \`code\``),
  ].join('\n');
}

/**
 * A long synthetic session: `size` records alternating a person's prompt and an agent turn, one
 * agent answer in ten long enough to be clamped, and a tool call in every agent turn.
 */
function syntheticSession(size: number): TranscriptRecord[] {
  return Array.from({ length: size }, (_, index): TranscriptRecord => {
    const id = `perf-${index}`;
    if (index % 2 === 0)
      return {
        id,
        role: 'user',
        blocks: [{ kind: 'text', id: `${id}:0`, text: `Please check **fixture** ${index}.` }],
      };
    return {
      id,
      role: 'assistant',
      blocks: [
        {
          kind: 'text',
          id: `${id}:0`,
          text: index % 20 === 1 ? longAnswer(index) : answer(index),
        },
        {
          kind: 'tool_call',
          id: `${id}:1`,
          name: 'Bash',
          callId: `call-perf-${index}`,
          input: { kind: 'text', text: `synthetic-tool --n ${index}` },
          outcome: { state: 'ok', output: { kind: 'text', text: 'ok' } },
        },
      ],
    };
  });
}

function assistantTexts(records: readonly TranscriptRecord[]) {
  const texts = records
    .filter((record) => record.role === 'assistant')
    .flatMap((record) => record.blocks)
    .filter((block) => block.kind === 'text')
    .map((block) => block.text);
  return {
    short: texts.filter((text) => !exceedsClamp(text)).length,
    long: texts.filter((text) => exceedsClamp(text)).length,
  };
}

it('parses only the answers on screen, and never an unchanged one twice', () => {
  const records = syntheticSession(40);
  const { short, long } = assistantTexts(records);
  expect(long).toBeGreaterThan(0);

  const { rerender } = render(<SessionTranscript records={records} />);
  // A person's prompt is never parsed, and a clamped answer is not parsed until it is opened.
  expect(parses.count).toBe(short);

  // Re-rendering the transcript — a reveal request, a row opened — parses nothing again.
  act(() => {
    rerender(<SessionTranscript records={records} reveal={{ token: 1, blockId: 'perf-3:1' }} />);
  });
  fireEvent.click(screen.getAllByRole('button', { name: /Ran 1 command/ })[0]);
  expect(parses.count).toBe(short);

  // Opening one long answer parses that one answer, once.
  fireEvent.click(screen.getAllByRole('button', { name: 'Show the rest of this block' })[0]);
  expect(parses.count).toBe(short + 1);
  // Closing it keeps no parse around; opening it again is one more.
  fireEvent.click(screen.getByRole('button', { name: 'Show less' }));
  expect(parses.count).toBe(short + 1);
  fireEvent.click(screen.getAllByRole('button', { name: 'Show the rest of this block' })[0]);
  expect(parses.count).toBe(short + 2);

  // A changed answer is parsed again; its unchanged neighbours are not.
  const changed = records.map((record) =>
    record.id === 'perf-3'
      ? {
          ...record,
          blocks: record.blocks.map((block) =>
            block.kind === 'text' ? { ...block, text: `${block.text}\n\nOne more line.` } : block,
          ),
        }
      : record,
  );
  act(() => {
    rerender(<SessionTranscript records={changed} />);
  });
  expect(parses.count).toBe(short + 3);
});

/**
 * Performance evidence on a large synthetic session. jsdom is slower than WebKit and lays
 * nothing out, so these are relative numbers: the same records, once with the agent's text
 * formatted and once with every record literal (as `system`, which is never formatted).
 * Printed for the report; the assertions hold the structural bounds rather than a wall clock.
 */
it('renders a 1,500-record synthetic session within its structural bounds', () => {
  const records = syntheticSession(1_500);
  const { short, long } = assistantTexts(records);
  const literal = records.map((record) => ({ ...record, role: 'system' as const }));

  const time = (input: readonly TranscriptRecord[]) => {
    const start = performance.now();
    const view = render(<SessionTranscript records={input} />);
    const elapsed = performance.now() - start;
    const region = screen.getByRole('region', { name: 'Session transcript' });
    const nodes = region.querySelectorAll('*').length;
    const characters = region.textContent?.length ?? 0;
    const start2 = performance.now();
    act(() => {
      view.rerender(<SessionTranscript records={input} reveal={{ token: 1, blockId: 'x' }} />);
    });
    const rerender = performance.now() - start2;
    view.unmount();
    return { elapsed, rerender, nodes, characters };
  };

  // Warm the module graph so the first measurement is not paying for imports.
  time(syntheticSession(20));
  parses.count = 0;
  const plain = time(literal);
  expect(parses.count).toBe(0);
  const formatted = time(records);
  expect(parses.count).toBe(short);

  console.info(
    `[transcript-markdown perf] records=${records.length} formatted-answers=${short} clamped-unparsed=${long}\n` +
      `  literal:   mount ${plain.elapsed.toFixed(0)} ms, re-render ${plain.rerender.toFixed(0)} ms, ${plain.nodes} nodes, ${plain.characters} chars\n` +
      `  markdown:  mount ${formatted.elapsed.toFixed(0)} ms, re-render ${formatted.rerender.toFixed(0)} ms, ${formatted.nodes} nodes, ${formatted.characters} chars`,
  );

  // The clamped answers cost a literal preview each and nothing else: no formatted subtree.
  // The DOM grows by the formatting of the short answers only — a bounded factor per answer,
  // not the size of the hidden payloads.
  expect(formatted.nodes).toBeLessThan(plain.nodes + short * 40);
  // Formatting drops syntax characters; it never adds the hidden remainder of a long answer.
  expect(formatted.characters).toBeLessThanOrEqual(plain.characters);
  // Two mounts and re-renders of 1,500 records take about two seconds alone, and more beside the
  // folder’s other suites. The limit is for a hang, not a speed claim — this test asserts none.
}, 30_000);
