import parse from 'spdx-expression-parse';
import { createHash } from 'node:crypto';

const allowed = new Set([
  'Apache-2.0',
  'MIT',
  'BSD-2-Clause',
  'BSD-3-Clause',
  'ISC',
  'OFL-1.1',
  'Unicode-DFS-2016',
  'MPL-2.0',
  'Zlib',
  'Unicode-3.0',
]);

export function acceptedLicense(expression) {
  const accepts = (node) => {
    if (node.conjunction === 'or') return accepts(node.left) || accepts(node.right);
    if (node.conjunction === 'and') return accepts(node.left) && accepts(node.right);
    return !node.exception && !node.plus && allowed.has(node.license);
  };
  try {
    return accepts(parse(expression));
  } catch {
    return false;
  }
}

export function renderNotices(entries) {
  const groups = new Map();
  for (const entry of entries) {
    if (!acceptedLicense(entry.license) || !entry.text?.trim() || !entry.package?.trim())
      throw new Error('A dependency has missing or unsupported license information.');
    const text = entry.text.replace(/\r\n/g, '\n').trim();
    const key = `${entry.license}:${createHash('sha256').update(text).digest('hex')}`;
    if (!groups.has(key)) groups.set(key, { license: entry.license, text, packages: new Set() });
    groups.get(key).packages.add(entry.package);
  }
  if (groups.size === 0) throw new Error('No dependency license texts were collected.');
  const lines = [
    '# Third-party notices',
    '',
    'Generated by `pnpm notices` from the locked Rust workspace and production npm dependencies. Local font notices are also distributed alongside the font assets.',
    '',
    'MPL-covered source is available through the versioned source links below. See [dependency license obligations](docs/DEPENDENCY_LICENSES.md) for redistribution and modified-source requirements.',
    '',
  ];
  for (const [key, group] of [...groups].sort(([a], [b]) => a.localeCompare(b, 'en'))) {
    void key;
    // A fence longer than any backtick run in upstream text keeps it literal.
    const fence = '`'.repeat(
      Math.max(3, ...[...group.text.matchAll(/`+/g)].map((m) => m[0].length + 1)),
    );
    lines.push(
      `## ${group.license}`,
      '',
      ...[...group.packages].sort().map((p) => {
        const cargo =
          /^cargo: ([a-zA-Z0-9_-]+)@([0-9]+\.[0-9]+\.[0-9]+(?:[-+][a-zA-Z0-9.-]+)?)$/.exec(p);
        return group.license.includes('MPL-2.0') && cargo
          ? `- ${p} — [Source archive](https://crates.io/api/v1/crates/${cargo[1]}/${cargo[2]}/download)`
          : `- ${p}`;
      }),
      '',
      `${fence}text`,
      group.text,
      fence,
      '',
    );
  }
  return lines.join('\n');
}
